language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - gfortran
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - binutils-dev

script:
  - mkdir build2 && cd build2
  - cmake .. && make && make test
