language: c
compiler:
  - gcc
  - clang

os:
  - linux
  - osx

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - gfortran
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - binutils-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update --quiet ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openmpi; fi


script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On && make install && ctest --output-on-failure

after_success:
  - make -k gcov
  - bash <(curl -s https://codecov.io/bash) -X gcov
