language: c

matrix:
  include:
    - os: linux
      compiler: gcc-4.4
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.4
            - g++-4.4
            - gfortran-4.4
      before_install:
        - export CC=gcc-4.4; export CXX=g++-4.4; export FC=gfortran-4.4
    - os: linux
      compiler: gcc-4.5
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.5
            - g++-4.5
            - gfortran-4.5
      before_install:
        - export CC=gcc-4.5; export CXX=g++-4.5; export FC=gfortran-4.5
    - os: linux
      compiler: gcc-4.6
      sudo: false
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
      before_install:
        - export CC=gcc-4.6; export CXX=g++-4.6; export FC=gfortran-4.6
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-4.6-trusty
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
      before_install:
        - export CC=gcc-4.6; export CXX=g++-4.6; export FC=gfortran-4.6
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-4.7
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.7
            - g++-4.7
            - gfortran-4.7
      before_install:
        - export CC=gcc-4.7; export CXX=g++-4.7; export FC=gfortran-4.7
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-4.8
      addons:
        apt:
          sources:
            - kalakris-cmake
          packages:
            - cmake
            - libopenmpi-dev
            - openmpi-bin
            - binutils-dev
            - gcc-4.8
            - g++-4.8
            - gfortran-4.8
      before_install:
        - export CC=gcc-4.8; export CXX=g++-4.8; export FC=gfortran-4.8

    - os: linux
      compiler: clang-3.4
      sudo: false
      before_install:
        - export CC=clang; export CXX=clang++
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang-3.5
      before_install:
        - export CC=clang; export CXX=clang++

    - os: osx
      osx_image: beta-xcode6.1
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi
    - os: osx
      osx_image: beta-xcode6.2
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi
    - os: osx
      osx_image: beta-xcode6.3
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi
    - os: osx
      osx_image: xcode6.4
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi
    - os: osx
      osx_image: xcode7
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi cmake
    - os: osx
      osx_image: xcode7.1
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi cmake
    - os: osx
      osx_image: xcode7.2
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi cmake
    - os: osx
      osx_image: xcode7.3
      compiler: gcc
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi
    - os: osx
      compiler: gcc-5
      before_install:
        - brew update --quiet >& /dev/null
        - brew outdated gcc || brew upgrade gcc
        - export CC=gcc-5; export CXX=g++-5
        - brew outdated cmake || brew upgrade cmake
        - brew install openmpi


addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - gfortran
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - binutils-dev


script:
  - mkdir travis && cd travis
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On -DSANITIZE_ADDRESS=On && make install && ctest --output-on-failure

after_success:
  - make -k gcov
  - bash <(curl -s https://codecov.io/bash) -X gcov
