# This file is part of P^nMPI.
#
# Copyright (c)
#  2008-2017 Lawrence Livermore National Laboratories, United States of America
#  2011-2017 ZIH, Technische Universitaet Dresden, Federal Republic of Germany
#  2013-2017 RWTH Aachen University, Federal Republic of Germany
#
#
# P^nMPI is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License as published by the Free
# Software Foundation version 2.1 dated February 1999.
#
# P^nMPI is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with P^nMPI; if not, write to the
#
#   Free Software Foundation, Inc.
#   51 Franklin St, Fifth Floor
#   Boston, MA 02110, USA
#
#
# Written by Martin Schulz, schulzm@llnl.gov.
#
# LLNL-CODE-402774

language: c

git:
  depth: 1000


# Install all main dependencies for Linux. Additional compilers may be installed
# as defined in the build matrix.
addons:
  apt:
    sources: &apt_sources
      - kalakris-cmake
    packages: &apt_packages
      - gfortran
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - binutils-dev
      - doxygen
      - help2man

# Install all required packages for OS X builds. The following solution was
# inspired by http://stackoverflow.com/a/20802381
before_install_tmpl: &before_install
  - brew update --quiet >& /dev/null
  - for pkg in gcc cmake mpich argp-standalone help2man doxygen; do
      if brew list -1 | grep -q "^${pkg}\$"; then
        brew outdated $pkg || brew upgrade $pkg;
      else
        brew install $pkg;
      fi
    done


matrix:
  include:
    # Ubuntu Precise (12.04 LTS) GCC builds.
    - os: linux
      compiler: gcc-4.4
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - gcc-4.4
            - g++-4.4
            - gfortran-4.4
      before_script:
      - export CC=gcc-4.4; export CXX=g++-4.4; export FC=gfortran-4.4
    - os: linux
      compiler: gcc-4.5
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - gcc-4.5
            - g++-4.5
            - gfortran-4.5
      before_script:
      - export CC=gcc-4.5; export CXX=g++-4.5; export FC=gfortran-4.5
    - os: linux
      compiler: gcc-4.6
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
      before_script:
      - export CC=gcc-4.6; export CXX=g++-4.6; export FC=gfortran-4.6

    # Ubuntu Trusty (14.04 LTS) GCC builds.
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc-4.6-trusty
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - gcc-4.6
            - g++-4.6
            - gfortran-4.6
      before_script:
      - export CC=gcc-4.6; export CXX=g++-4.6; export FC=gfortran-4.6
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc-4.7
      addons:
        apt:
          sources: *apt_sources
          packages:
            - *apt_packages
            - gcc-4.7
            - g++-4.7
            - gfortran-4.7
      before_script:
      - export CC=gcc-4.7; export CXX=g++-4.7; export FC=gfortran-4.7
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc-4.8
      before_script:
      - export CC=gcc-4.8; export CXX=g++-4.8; export FC=gfortran-4.8

    # Clang builds for Precise and Trusty.
    - os: linux
      compiler: clang-3.4
      sudo: false
      before_script:
        - export CC=clang; export CXX=clang++
    - os: linux
      dist: trusty
      sudo: false
      compiler: clang-3.5
      before_script:
        - export CC=clang; export CXX=clang++

    # OSX builds.
    - os: osx
      osx_image: xcode7.3.1
      compiler: clang
      before_install: *before_install
    - os: osx
      osx_image: xcode8
      compiler: clang
      before_install: *before_install
    - os: osx
      osx_image: xcode8.1
      compiler: clang
      before_install: *before_install
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      before_install: *before_install

    # OpenMPI builds.
    - os: osx
      osx_image: xcode8.2
      compiler: gcc-6
      before_install: *before_install
      before_script:
        - brew link --overwrite gcc
        - brew unlink mpich
        - brew install openmpi
        - export CC=gcc-6; export CXX=g++-6
      env:
        - OpenMPI
    - os: osx
      osx_image: xcode8.2
      compiler: clang
      before_install: *before_install
      before_script:
        - brew unlink mpich
        - brew install openmpi
      env:
        - OpenMPI

    # Build without Fortran.
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: false
      before_script:
        - export CMAKE_EXTRA_FLAGS="-DENABLE_FORTRAN=off"
      env:
        - NO_FORTRAN

    # Build with optimized configuration.
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: false
      before_script:
        - export CMAKE_EXTRA_FLAGS="
            -DENABLE_DEBUG=OFF
            -DENABLE_THREAD_SAFETY=OFF
          "
      env:
        - OPTIMIZED

    # Check release packaging. This will only package the current version,
    # unpack and change into this directory. The build will be done by the
    # default script below.
    - os: linux
      dist: trusty
      sudo: false
      compiler: gcc-4.8
      env:
        - DEPLOY
      before_script:
        - export CC=gcc-4.8; export CXX=g++-4.8; export FC=gfortran-4.8
        - export PWD_SAVE=$PWD
        - git clone https://github.com/Kentzo/git-archive-all.git
            ../git-archive-all
        - ln -s ../git-archive-all/git_archive_all.py
            ../git-archive-all/git-archive-all
        - export PATH="$PATH:$PWD/../git-archive-all"
        - mkdir package && cd package
        - ../extra/pack.sh
        - tar xfvz *.tar.gz
        - cd $(echo */)

    # Check coding convention.
    - os: linux
      dist: trusty
      sudo: false
      env:
        FORMAT
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-format-3.8
      git:
        submodules: false
        depth: 9999999
      before_script:
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch
      script:
        - git filter-branch --force --tree-filter '
            find . \( -name "*.c" -o -name "*.cpp" -o -name "*.h" \)
              -not -path "./externals/*"
              -exec clang-format-3.8 -style=file -fallback-style=none -i {} \; ;
            if test $(git diff | wc -l) -gt 0;
            then
                echo "";
                git --no-pager diff --color=always;
                exit 1;
            fi
          ' --tag-name-filter cat origin/master~1..HEAD
      after_success:

    # Check license in all files.
    - os: linux
      env:
        LICENSE
      addons:
        apt:
      git:
        submodules: false
        depth: 9999999
      before_script:
        - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        - git fetch
      script:
        - git filter-branch --force --tree-filter '
            num=$(wc -l extra/license/header.c | sed "s/[^0-9]*//g") ;
            find . \( -name "*.c" -o -name "*.cpp" -o -name "*.h"
                     -o -name "*.c.w" -o -name "*.h.w" -o -name "*.h.in" \)
              -exec sh -c "cat {}
                | head -n $num
                | git diff  --no-index -- extra/license/header.c -
              || (
                echo \"\";
                echo \"{} does not contain a valid license header.\";
                echo 1 > error
              )" \; ;

            num=$(wc -l extra/license/header.txt | sed "s/[^0-9]*//g") ;
            find . \( -name "*.txt" -o -name "*.conf" -o -name "*.yml" \)
              -exec sh -c "cat {}
                | head -n $num
                | git diff  --no-index -- extra/license/header.txt -
              || (
                echo \"\";
                echo \"{} does not contain a valid license header.\";
                echo 1 > error
              )" \; ;
            find . \( -name "*.sh" \)
              -exec sh -c "cat {}
                | head -n $((num + 2)) | tail -n $num
                | git diff  --no-index -- extra/license/header.txt -
              || (
                echo \"\";
                echo \"{} does not contain a valid license header.\";
                echo 1 > error
              )" \; ;

              test \! -f error ;
          ' --tag-name-filter cat origin/master~1..HEAD
      after_success:




script:
  - mkdir travis && cd travis
  - if [ "$TRAVIS_OS_NAME" != "osx" ] && [[ "$CC" != clang* ]];
    then
      SANITIZE_FLAGS="-DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On";
    else
      echo "Address Sanitizer is disabled for OSX and clang builds.";
    fi
  - if [[ "$CC" != clang* ]];
    then
      COVERAGE_FLAGS="-DENABLE_COVERAGE=On";
    else
      echo "Code coverage is disabled for clang.";
    fi
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug
      -DENABLE_TESTS=On -DBUILD_DOC_INTERNAL=On $SANITIZE_FLAGS $COVERAGE_FLAGS
      $CMAKE_EXTRA_FLAGS
    && make install
    && ctest --output-on-failure


after_success:
  - make -k gcov
  - bash <(curl -s https://codecov.io/bash) -X gcov
