language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - gfortran
      - cmake
      - libopenmpi-dev
      - openmpi-bin
      - binutils-dev

before_install:
  - pip install --user codecov


script:
  - mkdir build2 && cd build2
  - cmake .. -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On && make install && ctest --output-on-failure

after_success:
  - make gcov
  - codecov
